export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

export const SKILLS = {
  Frontend: [
    { name: 'React', icon: '⚛️', proficiency: 'Proficient' },
    { name: 'Tailwind CSS', icon: '🎨', proficiency: 'Proficient' },
    { name: 'Framer Motion', icon: '✨', proficiency: 'Intermediate' },
    { name: 'JavaScript', icon: '📜', proficiency: 'Proficient' },
    { name: 'HTML5', icon: '📄', proficiency: 'Proficient' },
    { name: 'CSS3', icon: '🎨', proficiency: 'Proficient' },
  ],
  Backend: [
    { name: 'Node.js', icon: '🟢', proficiency: 'Intermediate' },
    { name: 'Express.js', icon: '⚡', proficiency: 'Intermediate' },
    { name: 'REST APIs', icon: '🔌', proficiency: 'Intermediate' },
    { name: 'Socket.io', icon: '⚙️', proficiency: 'Intermediate' },
  ],
  Database: [
    { name: 'MongoDB', icon: '🍃', proficiency: 'Intermediate' },
    { name: 'Mongoose', icon: '🦁', proficiency: 'Intermediate' },
    { name: 'JSON', icon: '📋', proficiency: 'Proficient' },
  ],
  Tools: [
    { name: 'Git', icon: '🌿', proficiency: 'Proficient' },
    { name: 'Vite', icon: '⚡', proficiency: 'Proficient' },
    { name: 'npm', icon: '📦', proficiency: 'Proficient' },
    { name: 'Zustand', icon: '🔄', proficiency: 'Intermediate' },
  ],
};

export const PROJECTS = [
  {
    title: 'E-Learning Platform',
    description: 'Interactive e-learning platform for online courses and education',
    shortDescription: 'Online learning platform',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f70d504f0?w=500&h=300&fit=crop',
    technologies: ['HTML5', 'CSS3', 'React.js'],
    featured: true,
    systemArchitecture: 'Client-Server',
    frontend: ['HTML5', 'CSS3', 'React.js'],
    backend: [],
    database: [],
    devops: [],
    liveDemo: 'https://github.com/Rohitkurade/E-LearningPlateform',
    frontendCode: 'https://github.com/Rohitkurade/E-LearningPlateform',
    backendCode: '',
  },
  {
    title: 'Real Time Chat APP',
    description: 'Real-time messaging application with Socket.io for instant communication',
    shortDescription: 'Real-time messaging app',
    image: 'https://images.unsplash.com/photo-1611532736579-6b16e2b50449?w=500&h=300&fit=crop',
    technologies: ['React.js', 'Node.js', 'Express', 'Socket.io', 'CSS3'],
    featured: true,
    systemArchitecture: 'Client-Server',
    frontend: ['React.js', 'Socket.io-client', 'CSS3'],
    backend: ['Node.js', 'Express', 'Socket.io'],
    database: [],
    devops: [],
    liveDemo: 'https://github.com/Rohitkurade/Realtime_ChatApp',
    frontendCode: 'https://github.com/Rohitkurade/Realtime_ChatApp',
    backendCode: 'https://github.com/Rohitkurade/Realtime_ChatApp',
  },
  {
    title: 'TaskManager',
    description: 'Modern task management application with state management and local storage',
    shortDescription: 'Task management tool',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
    technologies: ['React 19.2.0', 'Vite 7.2.4', 'Tailwind CSS 4.1.18', 'Zustand 4.4.0'],
    featured: true,
    systemArchitecture: 'Single Page Application',
    frontend: ['React', 'Vite', 'Tailwind CSS', 'Zustand'],
    backend: [],
    database: [],
    devops: [],
    liveDemo: 'https://github.com/Rohitkurade/taskmanager_1',
    frontendCode: 'https://github.com/Rohitkurade/taskmanager_1',
    backendCode: '',
  },
  {
    title: 'GitHub User Finder',
    description: 'Search and explore GitHub users with detailed profile information',
    shortDescription: 'GitHub user search tool',
    image: 'https://images.unsplash.com/photo-1618401479427-9ada19b2b086?w=500&h=300&fit=crop',
    technologies: ['React', 'Vite', 'Tailwind CSS', 'Axios', 'GitHub API v3'],
    featured: true,
    systemArchitecture: 'Single Page Application',
    frontend: ['React', 'Vite', 'Tailwind CSS', 'Axios'],
    backend: [],
    database: [],
    devops: [],
    liveDemo: 'https://github.com/Rohitkurade/GitHub_User_Finder',
    frontendCode: 'https://github.com/Rohitkurade/GitHub_User_Finder',
    backendCode: '',
  },
];

export const EXPERIENCES = [
  {
    position: 'Computer Engineering Student',
    company: 'AISSMS College of Engineering, Pune',
    location: 'Pune, India',
    startDate: new Date('2023-01-01'),
    currentlyWorking: true,
    description: 'Strong academic foundation with focus on programming and software development. Actively building frontend and React-based projects. Practicing Data Structures and Algorithms for problem-solving.',
    technologies: ['DSA', 'Programming', 'Web Development'],
    website: '',
  },
  {
    position: 'Frontend Developer (Self-Learning)',
    company: 'Personal Projects & Practice',
    location: 'Remote',
    startDate: new Date('2024-01-01'),
    currentlyWorking: true,
    description: 'Built multiple React.js projects to strengthen component architecture. Hands-on experience with hooks, state management, and API integration. Continuously improving UI/UX and performance optimization skills.',
    technologies: ['React.js', 'Tailwind CSS', 'JavaScript', 'API Integration'],
    website: '',
  },
];
